In [7]:
import numpy as np 

#Создать массив из 10 нулей 
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
#Создать массив из 10 едииц
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
#Создать массив из 10 пятерок
b = [5]*10
print(b)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


In [12]:
#Создать массив из целых чисел от 10 до 50
f = np.arange(10,51)
print(f)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [13]:
#Создать массив из четных чисел от 10 до 50
d = np.arange(10,51,2)
print(d)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [15]:
#Создать матрицу 3х3 с числами от 0 до 8
c = np.arange(0,9).reshape(3,3)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [45]:
#Создать единичную матрицу 3x3
s = np.ones((3,3))
print(s)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [59]:
#Используйте NumPy для генерации случайного числа от 0 до 1
t = np.random.rand()
print(t)

0.8534205037304758


In [65]:
#Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
m = np.random.randn(25)
print(m)

[ 0.  0.  1. -1. -1.  0. -0.  0.  2. -1.  0.  0. -1. -1. -0. -2.  1.  0.
  1. -1. -1. -1.  1.  2.  0.]


In [43]:
#Создайте следующую матрицу используя функции библиотеки NumPy
l = np.linspace(0.01,1,100)
h = l.reshape((10,10))
print(h)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.10]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.20]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.30]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.40]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.50]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.60]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.70]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.80]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.90]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.00]]


In [47]:
#Дана стартовая матрица (обязательно запустите код ниже в вашем решении!). Эта матрица будет использоваться в последующих задачах. 

mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [50]:
##Необходимо написать код который вернет следующую матрицу из стартовой
mat = np.arange(1,26).reshape(5,5)
g = mat[2:,1:]
print(g)


[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [51]:
#Написать код обращения к элементу который вернет значение 20 из стартовой матрицы
mat = np.arange(1,26).reshape(5,5)
g = mat[3,4]
print(g)

20


In [54]:
#Написать код к стартовой матрице, который воспроизводит вывод, показанный ниже
mat = np.arange(1,26).reshape(5,5)
g = mat[:3,1]
print(g)

[ 2  7 12]


In [55]:
#Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
mat = np.arange(1,26).reshape(5,5)
g = mat[4,:]
print(g)

[21 22 23 24 25]


In [56]:
#Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
mat = np.arange(1,26).reshape(5,5)
g = mat[3:,:]
print(g)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [66]:
#Получить сумму всех значений в стартовой матрице mat
mat = np.arange(1,26).reshape(5,5)
c = np.sum(mat)
print(c)

325


In [68]:
#Получить стандартное отклонение в стартовой матрице mat
mat = np.arange(1,26).reshape(5,5)
c = np.std(mat)
print(c)

7.211102550927978


In [67]:
#Получить сумму значений в колонках в стартовой матрице mat
mat = np.arange(1,26).reshape(5,5)
c = sum(mat)
print(c)


[55 60 65 70 75]
